### ISSUE TITLE
Incorrect Steps data in the early morning time

### ISSUE THREAD

**Issue by jeydude1** [BIDMCDigitalPsychiatry/LAMP-platform#133]
Hi,

We are using mindLAMP 2 mobile app from Apple Store released on Dec 3 2020. We are noticing the steps data value is carried forward to next day in couchdb. 

Here is one of the test participant data

```
{
"data": [
  {
"timestamp": 1614607058052,
"sensor": "lamp.steps",
"data": {
"value": 34720
}
},
  {
"timestamp": 1614607055494,
"sensor": "lamp.steps",
"data": {
"value": 34715
}
},
  {
"timestamp": 1614607053358,
"sensor": "lamp.steps",
"data": {
"value": 34710
}
},
  {
"timestamp": 1614553344962,
"sensor": "lamp.steps",
"data": {
"value": 35279
}
},
  {
"timestamp": 1614553342403,
"sensor": "lamp.steps",
"data": {
"value": 35279
}
},
  {
"timestamp": 1614553339842,
"sensor": "lamp.steps",
"data": {
"value": 35279
}
},
  {
"timestamp": 1614553337277,
"sensor": "lamp.steps",
"data": {
"value": 35279
}
},
  {
"timestamp": 1614553334718,
"sensor": "lamp.steps",
"data": {
"value": 35279
}
}
],
}
```

Here is the date and time values
```
Timestamp |CST Date Time Time | Steps
1614553334718 | 2/28/21 5:02 PM | 35279
1614553337277 | 2/28/21 5:02 PM | 35279
1614553339842 | 2/28/21 5:02 PM | 35279
1614553342403 | 2/28/21 5:02 PM | 35279
**1614553344962 | 2/28/21 5:02 PM | 35279
1614607053358 | 3/1/21 7:57 AM | 34710**
1614607055494 | 3/1/21 7:57 AM | 34715
1614607058052 | 3/1/21 7:57 AM | 34720
1614607060610 | 3/1/21 7:57 AM | 34725

```

Is it possible to get daily step count?

**Comment by jijopulikkottil** [comment]
@avaidyam Currently for step count, we are getting value from the time of (start-time is) first login to the app. Can we set the start-time as the day beginning time in device's timezone ?

**Comment by avaidyam** [comment]
@jijopulikkottil I believe we discussed that the step count samples should be queried using a start time equivalent to the last access time? Then, after querying the data, the access time should be saved for the next check.

**Comment by jijopulikkottil** [comment]
@avaidyam [this](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/56 So for pedometer) was the last changes we done with step count as per the suggestion of consultant.
.Now we are using [listener](https://developer.apple.com/documentation/coremotion/cmpedometer/1613950-startupdates) for the changes rather than querying. And for HealthKit steps, we are using statistical query to get the cumulative data.

If we don't need cumulative result, we can do the same old [querying](https://developer.apple.com/documentation/coremotion/cmpedometer/1613946-querypedometerdata) pedometer and (HKSampleQuery)HealthKit data. Also we can test is there any chance to skip overlapping data!. We have done the same with sleep data and verified that we are able to get all overlapped data.

**Comment by avaidyam** [comment]
@jijopulikkottil It looks like this is the problem: 
> The data passed to your handler block represents the **cumulative data starting at the specified start date and ending at the current time**. You can get the start and end dates from the CMPedometerData object passed to your handler.

[Can you see if switching to this method improves things?](https://developer.apple.com/documentation/coremotion/cmpedometer/1778437-starteventupdates)

**Comment by jijopulikkottil** [comment]
@avaidyam this is an observer and we have to query the pedometer data using one of the above methods.. Let me try some and will update here.

**Comment by avaidyam** [comment]
We would like to get step count changes as they occur. (For example, 30 steps at 3pm, 12 steps at 6pm, etc.) They will be coalesced into day blocks or week blocks by client code during data analysis.

**Comment by jijopulikkottil** [comment]
@avaidyam 
I thought it can be do like getting the difference with previous. so in the same way we can can find the step count in a day. [From pedometer, didn't find a way to getting like 30 steps at 3 pm]
System is auto correcting the step count if there is multiple occurrences of step count from watch and mobile at same time.
So recommending to fetch the statistics data (cumulative result) even if we are able to get count changes (30 steps at 3 pm) from HealthKit.
----------------------------
Still if we need 'count changes' (30 steps at 3 pm), for Pedometer,  we can query data using custom time span using the last accessed time which we did at initial time.  Also for HealthKit, we can use statistical query by changing the `start time` when fetch on each interval. But this may mismatch with the data with device when system auto correcting the counts. Also for health kit step count, if we change the `start time` for the statistical result, we may be miss the watch step count, because the watch data will take some time to sync with the device.

**Comment by avaidyam** [comment]
@jijopulikkottil Could you try multiple methods to see which one comes up with the most accurate result when compared in the Apple Health app? 

> But this may mismatch with the data with device when system auto correcting the counts. Also for health kit step count, if we change the start time for the statistical result, we may be miss the watch step count, because the watch data will take some time to sync with the device.

Yes, this is a tricky one - do you have any ideas on how to solve this because I was under the impression that the query method we were using should do this automatically from Apple's end. And we can't filter the data because like you said, generated timestamp is different than the timestamp when the data was synchronized. 

Do we potentially submit all data for a whole day at the end of the day instead of as soon as we receive them? I feel like this is not an optimal solution.

**Comment by jeydude** [comment]
@jijopulikkottil, is it possible to get similar data and format as your mindlamp android app?

**Comment by jijopulikkottil** [comment]
@jeydude I will check and update here.

**Comment by jijopulikkottil** [comment]
@avaidyam 
1. For pedometer step count, we can collect daily steps. (we can get it by setting the start time as 'start of the day').
2. And for health kit steps, we can collect step count changes as they occur. (we can fix the 'missing steps' by keeping last saved timestamp per the source identifier) So we will get like e.g: 10 steps at 1 pm, 8 steps at 2 pm, 12 steps at 2:15pm etc).

**Comment by avaidyam** [comment]
@jijopulikkottil 

> For pedometer step count, we can collect daily steps. (we can get it by setting the start time as 'start of the day').

This makes sense, as long as we keep track of the last start time parameter used. 

> And for health kit steps, we can collect step count changes as they occur. (we can fix the 'missing steps' by keeping last saved timestamp per the source identifier) So we will get like e.g: 10 steps at 1 pm, 8 steps at 2 pm, 12 steps at 2:15pm etc).

This makes sense as well - sounds like a good plan!
