### ISSUE TITLE
Caching data in the UI for performance improvements

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#16]
In addition to caching the data so we don't make a network request each time we change tabs, we should also be considering correctly [using Progressive Web App features like ServiceWorker to help us work offline](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers) (i.e. no cell connection going through a tunnel, but I took a survey, and when my phone re-connects, it syncs that data up correctly).

**Comment by avaidyam** [comment]
Here are the core changes to be implemented based on our meeting this week (notes from @michaelmenon): 

- [ ] Material table will be replaced with list to take more control over data and as suggested useMemo can be used and split the components to small components.
- [ ] For each study – `LAMP.Participant.allByStudy(x.id`	- Studies and participants for each studies included with name and attachment value to.unityhealth.psychiatry.settings. If possible the sensor event data for indicators can be combined with the result to avoid per participant API calls. And expecting the result to sorted from API itself, so that we can correctly implement incremental loading.
- [ ] For each participant: `LAMP.Type.getAttachment(x.id, "lamp.name"))` - Combine with Participant API call.
- [ ] For each participant: `LAMP.Type.getAttachment(x.id, "to.unityhealth.psychiatry.settings"))` - Combine with Participant API call.
- [ ] For each participant: `LAMP.SensorEvent.allByParticipant(x.id, "lamp.analytics", undefined, undefined, 1))` - Combine with Participant API call.
- [ ] For each participant: `LAMP.SensorEvent.allByParticipant(x.id, "lamp.gps", undefined, undefined, 5))` - Combine with Participant API call.
- [ ] For each participant: `LAMP.SensorEvent.allByParticipant(x.id, "beiwe.gps", undefined, undefined, 5))` - Combine with Participant API call.
    - **THIS SHOULD BE REMOVED ENTIRELY**
- [ ] For each participant: `LAMP.SensorEvent.allByParticipant(x.id, "lamp.accelerometer", undefined, undefined, 5))` - Combine with Participant API call.
    - **THIS SHOULD BE REMOVED ENTIRELY**
- [ ] For each participant: `LAMP.SensorEvent.allByParticipant(x.id, "beiwe.accelerometer", undefined, undefined, 5))` - Combine with Participant API call.
    - **THIS SHOULD BE REMOVED ENTIRELY**
- [ ] For each participant: `LAMP.ActivityEvent.allByParticipant(x.id, undefined, undefined, undefined, 1))` - Combine with Participant API call.
- [ ] `LAMP.Type.getAttachment(researcher.id, "to.unityhealth.psychiatry.enabled")` - This can be cached in researcher login to avoid repeated calls.	
- [ ] `LAMP.Type.getAttachment(researcher.id, "lamp.selectedStudies"))` - This can be cached in researcher login to avoid repeated calls.
    - **THIS SHOULD BE IN LOCALSTORAGE INSTEAD**
- [ ] `LAMP.Type.getAttachment(researcher.id, "lamp.selectedStudies"))` - This can be cached in researcher login to avoid repeated calls.
    - **THIS SHOULD BE IN LOCALSTORAGE INSTEAD**
- [ ] For each study – `LAMP.Activity.allByStudy(study.id)` – Get sorted list of studies and activities under each study in single API call.
- [ ] In Learn, Prevent, Feed, Manage – `LAMP.Type.getAttachment` API is calling for each activity details like description and icon. Activity details need to be part of Activity object to improve performance. If possible add limits for event data(like last 1year or last 'n' number of events) under prevent section.
- [ ] Check if all required collections are properly indexed (Immediate)
- [ ] Separate User device notification tokan from Sensor data collection (Immediate)
- [ ] For all list pages, make the data load with pagination (Immediate)
- [ ] Review all API calls from the page, follow recommendations in API sheet (Immediate)
- [ ] REDUX based state managmnent for the UI (Immediate)
- [ ] Data caching using local DB like index DB, but if we use REDUX for state management we can cache the data in the REDUX store itself. so as to reduce frequent API calls and do quick loading. Then Use Web Workers to load data in the separate thread to update the REDUX store and IndexDB.  IndexDB will be used to save data for Offline scenarios. (Immediate)
- [ ] Identify slow rendering UI elements for optimization (Long Term)
- [ ] Should update check for UI elements in pages (Long Term)

**Comment by michaelmenon** [comment]
Please find the estimation for Phase 1 :
 
Splitting clinician UI components to small components and implementing API changes - 6days
Implementing web worker and IndexDB changes for Caching  
Initial setup - 3days
Implementation in clinician UI and prevent page -   5days
Implementation in other tabs - 5days
Testing - 2days
 
Total - 21days
 
ETA - On or before  01/03/2021 (If no other priority task in between) . This can be speed up based on Siju's availability after the game porting work.
 
After completing this phase 1 , Redux conversion can be started in a parallel development environment. Once we complete the IndexDB and service e worker implementation, it will be easier to move too Redux. Redux is a state management architecture just like Hooks functional state management that is being used now. Switching right away to Redux will take longer so we will complete Index DB / Web worker / making smaller components as an immediate fix and then later we can switch to Redux.

**Comment by sarithapillai8** [comment]
This task will not be finished in this milestone.

**Comment by sarithapillai8** [comment]
@avaidyam @elenamrv 

This optimization task along with https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/109 will be updated by March 12. These are inter-related tasks, that is why we are releasing together.
Thank you.

**Comment by ZCOEngineer** [comment]
@avaidyam @elenamrv 
After connecting to staging QA is able to test well and report issues which the dev team is able to fix quickly. Based on current pace we are planning to give you and Elena a preview by Wednesday morning EST time. We shall continue our QA while you take a test there. And by end of this week we shall finish the QA.

**Comment by sarithapillai8** [comment]
@avaidyam @michaelmenon @elenamrv 
PR added with changes related to this functionality changes[for clinician side]: 
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/181

The features covered : 

- Updated clinician side UI. Replaced material table with grid design. 
- API changes are using statically from the code api-staging.lamp.digital as lamp-core was not modified.
- Done with splitting components for clinician side. Typescript interface usage is not fully utilized as the corresponding changes required from lamp-core, since the modal objects are defined there. Otherwise tried to avoid usage of 'any'
- Data is now getting from new APIs and loaded and rendered with local Indexed DB.
- Participant, Sensor, Activity changes are almost done. Some minor bugs are still there. we are continuing our testing and bug fixing. 
[There is some issue with study count update with add/delete operations in the header for these 3 tabs, which is updated on refreshing the page. This will be fixed by tomorrow. ]
- Study based changes specified in https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/109 are almost done, but cloning functionality is not stable which can be rectified by tomorrow.
-Web worker is having some version issue after the security vulnerabilities fix. So it is not included in the build, but it is not affecting the performance. We will be looking on that.
- Some of code review fixes are also included in the build.

This is a major change. The performance improvement can be experienced with the changes, but testing need to be continued in both patient and clinician side until everything is stable. 

Thank you.
