### ISSUE TITLE
Patient list is not accurate, shows the wrong device and last active time

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#19]
> The last active column is often incorrect, says dashboard for people who were on Android app and time is often not updated for a long time
> Data Quality indicator only reflects quality of last data point ... could it be changed to say "Last passive data quality"?
> The data quality indicator is a bit misleading. If it changes color based on the last captured data point, how is this a measure of quality? Seems like calling it"last passive data" or something like that would make people understand it better

**Comment by sarithapillai8** [comment]
@avaidyam  this is done with the already existing code. Do you want to change the text by removing the text -quality? I can check for the last active device data.

**Comment by avaidyam** [comment]
Yes: 
1. Merge the `Last Active` column with the `Indicators` column as a bubble.
1. Rename the `Data Quality` bubble to `Last Data Ping`.

**Comment by Linoy339** [comment]
@avaidyam .  We can remove Last Active column.
 Just to confirm: 
1.Will the second bubble in Indicators column  have  label 'LAST ACTIVE'  ?
2.Is the same tool tip text  which is used in LAST ACTIVE column(present implementation) to be used  tool tip text in the above bubble(to be implemented) ?
If  its 'yes' to above questions, It will be like this :
![1_patientlist](https://user-images.githubusercontent.com/66460654/101759144-3d08f200-3aff-11eb-9808-b50c87162119.png)

**Comment by avaidyam** [comment]
@Linoy339 
1. Let's title the first bubble "Last Passive" and the second bubble as "Last Active". 
1. Yes - it should be the same tool-tip text, but please use the timestamp from the latest activity event instead.

**Comment by sarithapillai8** [comment]
@avaidyam 
Sorry, still left some confusions. Please confirm below -
1) 'Last passive' bubble tooltip content - the current data quality tooltip showing details of Gps, Accelerometer ?
2) 'Last active' - You said like showing same tooltip text but with timestamp from latest activity event. The tooltip shown on the screenshot was with data from sensor event. So do you mean we need to actually show the current text like  - '2hours ago on Android' with the timestamp from latest activity event instead of sensor event?

And just to confirm - we will be updating the analytics data(https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/12) with sensor events soon, so there will be meaningful data with sensor event then to show for 'Last active' column. Are you sure you want to use activity event data in this case?

**Comment by avaidyam** [comment]
@sarithapillai8 
1. Yes.
1. No, the tooltip should be the same as it is now, but with the latest activity event timestamp. 
1. Technically no - "Last Active" is supposed to refer to the last activity event submitted by the user. It's to help monitor patient engagement.

**Comment by sarithapillai8** [comment]
2. The device info we will get from sensor event. So we need to merge both information for the tooltip?
2hours ago on Android - timestamp from activity event and device info from sensor event?

**Comment by avaidyam** [comment]
@sarithapillai8 Yep, that's right.
