### ISSUE TITLE
Open API error

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#236]
I tried to convert mindLAMP Open API 3.x (https://api.lamp.digital/) to Swagger 2.0. Got error.

Tried to copy and past the content from https://api.lamp.digital/ to https://editor.swagger.io/. Noticed there is a error. Please let me know is it OK to modify type_id to id for /study/{id}/credential.

Also Please make sure Open API Schema is updated to your latest LAMP API Server changes. Thanks!

**Comment by avaidyam** [comment]
@jeydude [Please use the `openapi.yml` file in this (LAMP-platform) repository instead!](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/blob/master/openapi.yml) The definition will be updated for the server side at a later date due to some minor API inconsistencies introduced in the recent release -- sorry!
