### ISSUE TITLE
Slider survey question only showing question description

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#24]
> For slider questions, the value that gets saved in the ActivityEvent is the ‘option description’ not the option itself. For example if i create the question in the attached screenshot, see how the options differ from what is saved in activity event (2 more screenshots) 
> 
> Furthermore, it looks like none of the question descriptions or option descriptions are showing up at all...
![image1](https://user-images.githubusercontent.com/1361003/98568328-f82f3880-227e-11eb-92e9-3ea6e0b692b5.png)
![image2](https://user-images.githubusercontent.com/1361003/98568332-f82f3880-227e-11eb-8e77-8a1c282c91cc.png)
![image3](https://user-images.githubusercontent.com/1361003/98568334-f8c7cf00-227e-11eb-8a65-11b7856945d8.png)

**Comment by avaidyam** [comment]
@sarithapillai8 Any thoughts on the points I raised above?

**Comment by sarithapillai8** [comment]
1. Instead of showing (Select one) or similar non-customizable gray text underneath the question, show the question description.- okay
2. Instead of showing option descriptions next to the values like Value (Description), they should be shown underneath the Value as slightly gray text.-okay
3. We need to merge all of these tags: lamp.dashboard.tip_details, lamp.dashboard.survey_description, and lamp.dashboard.activity_details into the main Activity object. Do you have any suggestions on how the data should fit/be merged? - can we use a common name for tags - activity_details?

**Comment by avaidyam** [comment]
@sarithapillai8 I think using `activity_details` as the name for the `Tag` would work, but I think it makes more sense to just integrate the data into the `Activity` and `ActivitySpec` objects directly. I will share a document describing this soon as a new issue, so for now you can continue with (1) and (2) just for this issue.
