### ISSUE TITLE
Breathe Activities not working

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#286]
> When I click on one of the "Breathe" activities, I get taken to this blank screen. Audio doesn't even play.
![image](https://user-images.githubusercontent.com/82968538/120808862-7dc64e80-c517-11eb-8d28-427db4ddbeae.png)

**Comment by avaidyam** [comment]
@sarithapillai8 This needs to be resolved ASAP - can you please share what happened to break this previously working activity? //cc @ZCOEngineer @michaelmenon

**Comment by sarithapillai8** [comment]
@avaidyam 
Auto-build happens on updating an activity to the Lamp-activities repo which caused the issue. We were adding new activities  to the repo as part of repo conversion task. The production is not working with latest tagged commit. The .env file is generated through BuildEnv script in dashboard. Could you let me know how production release to be done with production value for REACT_APP_GIT_SHA? Currently activities are fetching from dist folder not with the latest tag?

This issue is fixed in production.
Thanks

**Comment by sarithapillai8** [comment]
@avaidyam 
I was referring the dist branch. not dist folder. It was wrongly written in comment. Sorry.

See the below lines of code. It is referring dist branch for staging and 'latest' tag for production.

let activityURL = "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/"    
activityURL += process.env.REACT_APP_GIT_SHA === "dev" ? "dist/out" : "latest/out"    
let response = await fetch(`${activityURL}/${demoActivities[activity.spec]}.html.b64`)

But I don't get where I can set the value for REACT_APP_GIT_SHA . I am not able to see the the .env file generated in production. In staging or local environment it is generated with 'dev' value. So what is actually happening is like always the dist branch files are fetching. Could you please correct me if there is some missing?

**Comment by avaidyam** [comment]
In both local and staging environments there is no tag on the current commit, so when the `git` command returns an error, the string `dev` is used instead. If you need to emulate a production tag scenario, create a new **annotated tag** on the current branch following the CalVer or SemVer format (i.e. `YYYY.mm.dd` = `2021.6.7` WITHOUT leading zeros and NO additional components like `.02`). Then, the build/start script should pick that up as the environment variable's value instead of `dev`.

**Comment by sarithapillai8** [comment]
Ok thanks @avaidyam .

**Comment by avaidyam** [comment]
@sarithapillai8 Please do not push these tags to origin! This should be strictly local for testing only.

**Comment by sarithapillai8** [comment]
@avaidyam 
I am doing through the interface - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/releases/edit/2021.6.7. Not with manual push. Is that what you mean?

**Comment by avaidyam** [comment]
If you are testing whether or not the correct tag will be used to load activities in the dashboard, you must use the `git` command line tool and NOT push the tag you create to origin. If you are making a production release, you should create a GitHub release (NOT a draft release).

**Comment by sarithapillai8** [comment]
@avaidyam 
I have updated the release through the URL - https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/releases/new. Entered the details, give the tag name and selected specific branch (dist in case of lamp-activities and master in case of dashboard). Then click on push the release button, not the draft. So this created new tag with new release. Why do we need git command tool? The naming convention I used was wrong. I did with leading zeros.

**Comment by avaidyam** [comment]
That is the correct process if you are pushing a new production release. I was under the impression you wanted to test locally whether the right branch/tag name would be selected based on the value of the environment variable. If not, then the release should work correctly.

**Comment by sarithapillai8** [comment]
My concern is - I am doing the release in this way for both activities and dashboard repos. But the activity URL in the production is not https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/latest/out/<activity.b64.html>, instead it is fetching https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/dist/out/<activity.b64.html>. So it seems the env variable(REACT_APP_GIT_SHA ) is not correctly setting from production. I need to know this tag will help to work this correctly?  I don't see that working.

**Comment by avaidyam** [comment]
That is why I suggested using the git commands locally to test the value of the environment variable correctly. If you are trying to test something out you should NOT be creating a production release through the GitHub UI at all. Please test locally first and check what the value of the variable is.
