### ISSUE TITLE
Activities available on dashboard but not on mobile app

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#315]
> Surveys and Cognitive tests are in the correct group and show up in the Assess page of the dashboard in Chrome, but on the app itself for iPhone only Cognitive Tests show up on the Assess page.
> ![image](https://user-images.githubusercontent.com/82968538/124190484-57e98680-da90-11eb-8c28-f398ae268417.png)
>![image](https://user-images.githubusercontent.com/82968538/124190493-5d46d100-da90-11eb-8f11-70c1e2d653f6.png)

**Comment by divyav2020** [comment]
We are unable to reproduce this issue

**Comment by divyav2020** [comment]
We are unable to reproduce this issue.  We request you to clear the cache and retest.

**Comment by divyav2020** [comment]
We are unable to reproduce this issue.  while we try to find this issue, for the time being could you please logout and login back to see the screen updates correctly?

**Comment by tlakhtak** [comment]
The issue persists when logging in again. This issue is occurring for mindLAMP users on a different server to ours.

**Comment by michaelmenon** [comment]
Thanks, @tlakhtak  could you please confirm the LAMP server on which you are seeing this issue is working as a docker container ? Just want to make sure the server environment is the same.

Also could you confirm that the iPhone Safari is the latest version on the iPhone ? Please let us know and we will see if you need to update your server with the latest server in the MindLamp production server.

**Comment by tlakhtak** [comment]
Dashboard was seen on Chrome on desktop, which is the latest version. LAMP server is working as a docker container.

**Comment by avaidyam** [comment]
FYI @michaelmenon - Tanvi L (@tlakhtak) and Suraj (@SuruPa00) are part of the BIDMC team and refer to the BIDMC servers/resources.

**Comment by sarithapillai8** [comment]
We are still unable to reproduce this. To debug this particular issue, could you please provide the participant and researcher details? In the screenshot the participant id is not clear.

**Comment by michaelmenon** [comment]
Hi @avaidyam  but  Tanvi in her post said : This issue is occurring for mindLAMP users on a different server to ours.

What does that mean, are the users connecting to any other server where LAMP is hosted ? 

Also @tlakhtak can you update the Chrome to latest version of the Chrome and check, we will try to reproduce on our end but like @sarithapillai8  said could you please send us the participant and researcher details for us to check.

**Comment by tlakhtak** [comment]
The server running LAMP that is having this issue has the domain name sangath.psych.digital. All participants under researcher 'Jayesh Kudav' are having this issue.

**Comment by divyav2020** [comment]
We logged in to the server you provided, using Admin credentials and was unable to reproduce the issue (kindly refer to the screenshot).
So request you to provide us with the user credentials that produce the issue when you tested.
![IMG_3385](https://user-images.githubusercontent.com/74397668/124925805-744e6b80-e01a-11eb-96a6-a6b5dee97b31.PNG)

**Comment by tlakhtak** [comment]
> The same user, when logging in with user credentials, is experiencing the issue.
>![IMG_0069](https://user-images.githubusercontent.com/82968538/124927956-2cedbe00-dfcd-11eb-82a6-9f3eabc8dd9f.PNG)

**Comment by sarithapillai8** [comment]
@tlakhtak Could you please provide the password also?

**Comment by tlakhtak** [comment]
log-in: U3310164650@lamp.com, pass: U3310164650

**Comment by sarithapillai8** [comment]
@avaidyam  
We got the issue and it is because we are having a condition like ignore the survey activity for server ending with - psych.digital in one function_hideCareTeam()

(LAMP.Auth._auth.serverAddress || "").includes(".psych.digital")
 
Can you please confirm we can remove this condition? If you can confirm it , I can remove it now.

**Comment by avaidyam** [comment]
@sarithapillai8 Yes, please do remove this.

**Comment by sarithapillai8** [comment]
Updated in production
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/pull/273
