### ISSUE TITLE
Back button not functioning for Jewels

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#319]
>Back button is present but not functioning. Users have to exit the app completely and restart to return to the main dashboard.

**Comment by divyav2020** [comment]
The issue is not occurring during our testing. (Kindly refer to the video attached).  The issue could be related to browser cache, so kindly clear it before retesting.

https://user-images.githubusercontent.com/74397668/125080622-aa572280-e0e2-11eb-8f14-40a9e19a03d9.MOV

**Comment by jtorous** [comment]
Hello,

Thank you for looking into this! What happens if you complete the test
(touch all of the jewels?). What happens if you push the back button?

Thanks,
John

**Comment by divyav2020** [comment]
Scenario 1: What happens if you complete the test (touch all of the jewels?) - Display shows "Congrats" and moves back to Assess screen

Scenario 2:  What happens if you push the back button? -  Display moves back to Assess screen
(Kindly refer to the videos attached)

https://user-images.githubusercontent.com/74397668/125091442-08d5ce00-e0ee-11eb-8125-0bc670f30dd1.MP4


https://user-images.githubusercontent.com/74397668/125091530-1f7c2500-e0ee-11eb-8faf-ac57d35ac505.MP4
