### ISSUE TITLE
Refresh in user settings redirects to all users page

### ISSUE THREAD

**Issue by dcurrey88** [BIDMCDigitalPsychiatry/LAMP-platform#341]
**Describe the bug**:
If you refresh the page in the settings for a user, it takes you back to all users. It should stay on the page.

**Comment by michaelmenon** [comment]
Hi @avaidyam , It is how the system was developed and not an issue.  This will require some good amount of time and testing. Please confirm if we need to spend time on this.

**Comment by michaelmenon** [comment]
Also if we need to do this we need to do it for each inner page and all the tabs.

**Comment by avaidyam** [comment]
@michaelmenon This is not how the dashboard was designed to work and it is a bug. If the user is on a patient's profile/settings page, the URL should be `.../#/participant/U123456789/settings` - and if the page is reloaded, this URL should be used to redirect the clinician/user to the same page they were at before. If this URL link is clicked, the log in screen will display if the user is not already authenticated, and then take the user directly to this page. The bug is in the routing system in `App.tsx`.

**Comment by michaelmenon** [comment]
@avaidyam this is how the system logic works now.  if it needs to changed like I said it's going to take some time. check with your team and let us know the priority on this and team will work on this.

**Comment by avaidyam** [comment]
Please change the logic to match what I described.

**Comment by sarithapillai8** [comment]
@avaidyam 
Do we need to change the logic of all sub pages like this? for eg : activity add/edit, activity pages etc

**Comment by avaidyam** [comment]
Yes, this needs to work for any and all pages across the UI.

**Comment by sarithapillai8** [comment]
@avaidyam @michaelmenon @tlakhtak The changes are updated in dashboard-staging. QA started testing on dashboard staging.
