### ISSUE TITLE
Markdown not working

### ISSUE THREAD

**Issue by SuruPa00** [BIDMCDigitalPsychiatry/LAMP-platform#345]
Markdown isn't working at all. See Screenshots
<img width="1413" alt="cygmTrt2_o" src="https://user-images.githubusercontent.com/86117379/128391988-2b7c7636-0622-4d65-be77-0b606cba7506.png">
<img width="1416" alt="jiPmCIwe_o" src="https://user-images.githubusercontent.com/86117379/128391997-8e1b7320-33f1-4ad8-8fdd-0409bda87cc4.png">

**Comment by sijugeorge-zco** [comment]
@SuruPa00 @avaidyam 

As per our requirement and earlier discussions we were using **react-markdown** . Please check https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/338

We cannot add HTML tags directly , because it won't support for the markdown (https://www.npmjs.com/package/react-markdown). Please check the supported Markdown types (https://commonmark.org/help/)

If we need to support HTML tags , we need to use any editors like **CKEditor** .

Please let us know whether we need to change it to use any editors.

**Comment by avaidyam** [comment]
@sijugeorge-zco This is absolutely not correct - React Markdown does support HTML. In fact, this issue has been reported before twice [and I have manually resolved it before both times, as shown in this commit, by adding `allowDangerousHtml={true}`](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/commit/f36eda20950f86497c697aeea0a84ecf830a12ef). Please ensure that this kind of repeated regression/loss of function does not happen in the future. // cc @lukeoftheshire

**Comment by ZCOEngineer** [comment]
We shall check on this an update @avaidyam

**Comment by sarithapillai8** [comment]
https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/commit/198541f998bf68c302c411f3ae30ce12bea88c2c - updated LAMP-activities with the fix. Updated in production.

**Comment by SuruPa00** [comment]
This is broken again: see image below for what happens when markdown is written in the description - it outputs as literal text instead

<img width="473" alt="Screen Shot 2021-09-07 at 2 50 25 PM" src="https://user-images.githubusercontent.com/86117379/132396247-005b7424-3976-4bd9-8482-f966be323114.png">

**Comment by sijugeorge-zco** [comment]
@SuruPa00
This was due to the Auto build issue for the Tips. We will update this again.

**Comment by SuruPa00** [comment]
It's working now, thanks.
