### ISSUE TITLE
Add undelete method(s) to the LAMP API

### ISSUE THREAD

**Issue by lukeoftheshire** [BIDMCDigitalPsychiatry/LAMP-platform#433]
It can be frustrating to accidentally delete an activity in LAMP as it is currently very difficult to recover. This issue can be exacerbated by technical issues that cause activities that should not be deleted to be deleted (see https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/379 for an example).

As such, it would be nice to have some sort of 'undelete' functionality added to the LAMP API that allows a user to change the deleted tag on a resource back to False.

**Comment by lukeoftheshire** [comment]
In addition to this, it would be nice to have a parameter such as "get_deleted" for things like LAMP.Activity API calls that fetches deleted activities - as the ActivityEvents persist even if an Activity is deleted, this would be helpful for analyses.

Currently, the only way I am aware of to do either of the things described in this issue is to manually interact with the database which is probably not how it should be.

**Comment by avaidyam** [comment]
> it would be nice to have some sort of 'undelete' functionality

This is covered in the feature request #263 (`Potentially, implement an undelete or a restoreVersion operation...`). 

> it would be nice to have a parameter such as "get_deleted" for things

As proposed in #263, it would be possible to query the system audit log for deleted entries instead of directly interacting with the database (which is, as you correctly point out, **highly discouraged**). 

Let's move this discussion to #263 - and please do suggest there a potential workflow (and accompanying API if you have ideas) on how a system administrator would query the audit log and restore a deleted Activity or produce a list of still-deleted Activities (filtered by deletion time range, deletion reason, parent ID, object properties, etc.).
