### ISSUE TITLE
App crashing, unable to open

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#468]
Many users across many servers have reported difficulty loading the app and it's various features, encountering an endless loading circle. Here is an example of that with an Android device.

https://user-images.githubusercontent.com/82968538/148968966-baec3f7b-4ebd-48d5-8d24-c7e33e147ed7.mp4

**Comment by tlakhtak** [comment]
This app crash is not resolved as of this morning. No additional details at this time but will provide as we know more.

**Comment by michaelmenon** [comment]
Hi @tlakhtak  please let us know if its resolved or not.. And are these users connected to the LAMP production server ?

**Comment by avaidyam** [comment]
@michaelmenon We're not seeing the issue on our team's devices right now, at least in our QA testing pass. @tlakhtak and @akmeyer3 are working with patients to determine what's causing the issue, or if [the issue was resolved by this.](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/464#issuecomment-1009701807)

**Comment by michaelmenon** [comment]
Thanks @avaidyam , we also checked the production, team checked all the activities in Android (Samsung M21 (Version 11)) and its working fine.

**Comment by avaidyam** [comment]
Closing this issue until we are clearly able to determine if it is still ongoing and potential causes.
