### ISSUE TITLE
Temporal Order Test

### ISSUE THREAD

**Issue by Linoy339** [BIDMCDigitalPsychiatry/LAMP-platform#569]
This is a game to remember pictures displayed. The order and sequence of the pictures has to be remembered and need to tap when required

**Comment by ZCOEngineer** [comment]
QA testing is in final stages

**Comment by divyav2020** [comment]
We have updated in staging server.
[LAMP_Admin Website_Memory Game.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8652120/LAMP_Admin.Website_Memory.Game.xls)

**Comment by sarithapillai8** [comment]
For the memory task

It should start with three learning/encoding trials in a row. Each trial should have the same items/location/order.

This is followed by a 60 second delay during which orientation questions are asked.

After delay, there should be a testing/recall trial, but no more learning trials.

 

This sequence is invariable.

Each time a Memory task is run there should be

instructions
3 learning trials (same items and location and sequence)
60 second delay along with orientation question
1 testing/recall trial (to test whether subjects remember the items/location/sequence)
Once completed, the task resets with a new set of items and location and sequence but runs through the sequence of instruction, 3 learning trials, delay, recall.

 

I've attached a pdf of the whole sequence.
[Temporal Order Test - smartphone.pdf](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8896579/Temporal.Order.Test.-.smartphone.pdf)

I can send you a video of what the game should look like, if you think this would be helpful, or you can go to

https://www.iboca3.com/ (use any number or letter as password) under MEM to see a prototype.

**Comment by sarithapillai8** [comment]
The animation interval for each item should be 2 seconds. The first item interval is about 4 seconds, second item is about 0.5 seconds, and third seems about 2.5 seconds.
Would it be possible to put the instructions right under the grids? The current location is hard to notice. Would this make the screen too busy?
Autocorrection is confusing. Lots of things flash and grey in and out.
If I choose the wrong item, all the incorrect options grey out (this is nice), but only for 2 seconds. Can you program it so that it stays greyed out (and correct option stays colored - so subject knows which is the correct item) until the subject chooses the location?
Similarly, if the subject correctly choses the item, can you have all they incorrect items grey out (to tell subject they made the correct choice) until the subject choses the location?
Currently the testing/recall trial (after the 60 second delay) is not a recall trial.  It introduces another 3 items/locations. It should just be a blank 3x3 grid on the left and the 9 items on the right and should be recording the subject's ability to remember the previous presented learning trials.
For the orientation questions - can you include more options for the year? Maybe 10 years prior and 5 years after current year (2012 - 2027)
The algorithm for choosing the items and foils should be (sorry, I may have confused things)
For 3 items memory task
Randomly choose 3 of the 12 categories
Randomly choose 1 item from each of the 3 chosen categories as the item/target
Randomly choose 2 out of the remaining 3 pictures in each category as the foils
For Example
Buildings, Insects, Music randomly chosen categories
Lighthouse, Mosquito, Harp randomly chosen as the target pictures from the above categories
Lighthouse/Temple, Beetle/Scorpion, Drum/Violin randomly chosen from the categories as the 6 foils.
 

 

Settings

Target Sequence Length should remain variable at 3 or 4 (controlled from the Website)

Foils = 2 (9 options with 3 targets and 12 options with 4 targets)

Grid Size = 3x3

Encoding Trials = 3

Delay = 60 seconds

Animation Interval = 2 sec

Post-animation persistence = 1 sec

**Comment by sarithapillai8** [comment]
This looks really good. Everything up to the end of the delay seems great.

 

At the recall/recognition phase, there still is another learning sequence, which needs to be removed. It should just be a blank 3x3 grid on the left and the 9 items on the right and should be recording the subject's ability to remember the previously (before the delay) presented items/location.

 

There also should not be any autocorrection during this recall/recognition phase. It should allow the subject to select any image and any location and should end after the subject chooses the third location (or fourth location - if we are running the 4 item memory task).

**Comment by divyav2020** [comment]
We have updated in staging server.
[LAMP_Admin Website_Memory Game_Update.xls](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/8946126/LAMP_Admin.Website_Memory.Game_Update.xls)

**Comment by sarithapillai8** [comment]
Change Request:
-For the final recall/recognition task, can you make it so that it just reflects what the patient chooses. Right now, if the patient chooses an incorrect image or incorrect location then nothing shows on the answer grid. An item only shows up on the answer grid if it is the correct item and correct location. I would like the item selected to display on the location selected regardless of whether it is correct or incorrect, otherwise it can be confusing to the patient. This applies only to the final recall/recognition task.

 

-The program seems to autocorrect after about 3.5 seconds. Can we change the autocorrection delay for the learning trials to about 8 seconds?

 

-Data collected would be response time per screen touch, actual response (which item or location selected) and correct/incorrect. In other words

The program should keep track of item selected as correct/incorrect as well as the actual item (each item can be assigned a number)
The program should keep track of location selected as correct/incorrect as well as location (again, each location can be assigned a number)
The program should keep track of the time it takes to select each and every item and each location as well as the total time to do each learning task and final recall/recognition task.
Data collection for all 3 learning trials and the final recall/recognition test.

**Comment by avaidyam** [comment]
@sarithapillai8 Please re-open issues in addition to re-labeling if additional work is required on them.

**Comment by sarithapillai8** [comment]
Response after update - 
The game is about 99% ready and looks awesome.

program still crashes occasionally, but I have not been able to reliably reproduce it.

During the learning trials, if I make a lot of errors by tapping random items and locations multiple times, the program will sometimes not advance to the next phase. It will catch at the transition and just show a blue screen.

For the 4 item learning and the 3x4 answer grid, the bottom 3 items are off the screen - see photo.
For the final recall phase (see same photo), if I choose the wrong item, i.e., the sunflower, it greys out but the other items stay in color. Is it possible to flip this? So that the chosen item, regardless of it being correct or incorrect, stays in color and all of the other items grey out? Just for the final recall phase.

**Comment by divyav2020** [comment]
@avaidyam Game is ready for production push

**Comment by carlan1** [comment]
Game functions as intended in staging.
