### ISSUE TITLE
Unable to log in on mobile apps with valid credentials.

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#61]
> **Collaborator**: "ERROR" about wrong server showing up when logging in. LAMP threw an error when my participant tried to log in and asked if she was on the right server
>
> **Collaborator**: One of the participants has to log in every time he quits the app as well. (Android)

![image](https://user-images.githubusercontent.com/1361003/101496290-958d9300-3937-11eb-985b-16bb63ef6db6.png)

**Comment by elenamrv** [comment]
Hi @michaelmenon - many of our patients are telling us this is occurring for them on both android and apple devices. It is a huge problem because it means we are not collecting data if no one can log in to their account. Please let me know what the plan is to identify why this is happening and fix it ASAP. I am happy to get on a phone call.

Thank you so much!

**Comment by michaelmenon** [comment]
@elenamrv Sure, we are checking on it and will let you know a status update omg it asap. I will let you know if we need any details on on this issue.

**Comment by ZCOEngineer** [comment]
Hi @avaidyam 
Is it possible to get one credential which is having this issue?

**Comment by avaidyam** [comment]
@ZCOEngineer I've sent you and the team the information privately in Basecamp. Thanks!

**Comment by sarithapillai8** [comment]
@avaidyam 
Siju added a pull request with the fix. Please let us know if that solve the issue.
