### ISSUE TITLE
CouchDB to MongoDB migration

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#631]
Hi,

Recently we had few issues with CouchDB
1. While submitting multiple delete requests with CouchDB, CouchDB got into corrupted status 
2. While CouchDB was doing data compression, CouchDB got into corrupted status 

We are thinking to migrate CouchDB to MongoDB.

I believe mindLAMP platform supports MongoDB, what steps do we need to follow for migrating CouchDB to MongoDB.

We are in the middle of the some of the studies. Any recommendation for smooth migration?

**Comment by avaidyam** [comment]
> While submitting multiple delete requests with CouchDB

We do not support the ability to directly manipulate or interface with the platform's underlying database. The `server` module operates under the assumption it (or multiple coordinating instances of the server) is the only actor reading, writing, updating, or deleting documents from the database.

> While CouchDB was doing data compression, CouchDB got into corrupted status

Unfortunately, we can't offer any support for CouchDB itself; you'll need to make an issue or seek help using their official channels separately for this. 

> mindLAMP platform supports MongoDB

Yes, however, it's been in the beta phase since early May of last year (2021) and we expect it to be ready for general use in the coming weeks as we work to add documentation around it. 

> what steps do we need to follow for migrating CouchDB to MongoDB

We do not and cannot support migration from CouchDB to MongoDB; we've tried this a few times and the database inconsistencies are significant enough to avoid it. 

> Any recommendation for smooth migration?

Unfortunately, we cannot recommend you migrate at this time if you have active studies. You are more than welcome to set up a second server for new studies that uses MongoDB and then maintain the two servers separately.
