### ISSUE TITLE
Studywide Missing Accelerometer Data

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#664]
**Describe the bug**
For a study on mindLAMP we are experiencing patient wide missing data. Multiple participants (though not all) have continuously opened the app, and kept their devices out of airplane/low power mode. Several participants in the study have received appropriate screen state data. Notably, the participants missing data are not COMPLETELY missing data, as a raw data pull and check of the dashboard were able to show that some data is being collected, just at very low levels. This doesn't appear to be a systemwide issue, as another of our team is having no issue collecting accelerometer data. 

Researcher id: ysfm3gmsy2fyvfgxgjpr
Study id: cpm1207zqaj2rdw81v9a

**Expected behavior**
Participants in the study should receive 'good' levels of accelerometer and screen state data, appearing as green in the blocks of the screenshot below. 

**Screenshots**
This is the screenshot of our data quality check this morning. We are expecting to see green bars in the majority of users for both accelerometer & screen_state data. GPS being gray is expected. 
![dataqual](https://user-images.githubusercontent.com/104088715/176024514-ced872d1-86dd-4f44-b59e-209db9c536d1.JPG)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: [iOS 15.5]

 - Device: iPhone 8+
 - OS: [iOS 15.5]

**Comment by lukeoftheshire** [comment]
This issue has been resolved by https://github.com/BIDMCDigitalPsychiatry/LAMP-cortex/pull/139 - the true issue was a small bug with the visualization script incorrectly looking at GPS data instead of accelerometer - so for studies with accelerometer but no GPS data false results could appear.

Accel data was still being collected though!

I'm going to close this issue since the true cause was diagnosed but please re-open if there are further issues. Thanks for the detailed write-up, @ertjlane!
