### ISSUE TITLE
mindLAMP Dashboard Data Report

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#671]
**Describe the bug**
On the mindLAMP dashboard, the tag 'last active data' has been providing reports of active data inconsistent with the data portal. The tag further appears green, despite reporting 'never'. 

**Expected behavior**
The recent active data tags show the most recent active data shown in the portal, and if there are none, appear gray, rather than green.

**Screenshots**
<img width="1205" alt="Screen Shot 2022-07-22 at 11 08 11 AM" src="https://user-images.githubusercontent.com/104088715/180468966-9d708534-bef6-40b3-94eb-cf5c12113e18.png">

<img width="1197" alt="Screen Shot 2022-07-22 at 11 45 11 AM" src="https://user-images.githubusercontent.com/104088715/180475777-2564c19a-1647-4642-bf41-97a4b51868b5.png">

**Desktop (please complete the following information):**
 - OS: [OS Monterey]
 - Browser [chrome]
 - Version [12.2.1]

**Comment by sarithapillai8** [comment]
@avaidyam 
The tag color appearing for both active and passive data are based on the passive data(gps/accelerometer). Tooltip is showing based on last activity event data for "Last Active" and sensor data for "Last passive". Is it to ok show different colors for the tag? The code from old version also showing the same. That same functionality was reusing here.

https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/rev-coding/src/components/ParticipantList.tsx#L766
https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/rev-coding/src/components/ParticipantList.tsx#L992

**Comment by avaidyam** [comment]
@sarithapillai8 Yes, the colors should be different and it looks like the code to show that exists. Why isn't it working?

**Comment by sarithapillai8** [comment]
@avaidyam 
The colors will be same as both based on passive data now. Tooltip shows the correct data. I can change it to show based on last activity event data. 
One more think to confirm - 'Last active' is actually considering latest activity event data timestamp. The tooltip includes the latest activity event timestamp and the last login time in brackets. So these values might not match all the time. User might have logged in recently, but with old activity event data. Is there any change required? What is actually expected there?

**Comment by sarithapillai8** [comment]
@avaidyam One more thing to clarify. Do we need to show latest update by fetching the data frequently?

**Comment by avaidyam** [comment]
No, you don't have to show the latest data always. I'm not sure what you mean by the proposed change. Can you provide an explanation/diagram/mockup?

**Comment by sarithapillai8** [comment]
![image](https://user-images.githubusercontent.com/63710347/181282315-b8bc2bee-e3ad-4f41-85d5-14ae0d593faf.png)
Like you can see, the tool tip showing different date range. In brackets you can see last login date time and 3weeks ago is the latest activity event submission date time. I was asking about this. What is actually expected here?
Note: This screenshot is after changing 'Last Active' tag color change with correct active data in development environment. Not available in dashboard-staging. Otherwise the colors will be same.

**Comment by avaidyam** [comment]
I don't think anything else is necessary here. The issue was that "Never" would show as green and if that has been fixed, it should be fine.

**Comment by sarithapillai8** [comment]
I hope the date time showing in tooltip is fine. I asked for the clarification because it is little bit confusing. 3 weeks ago an activity event generated, but last login done today. Color changes are done and QA testing on that was completed in ZCO staging. We can update it in dashboard staging now if no more changes are required.

**Comment by avaidyam** [comment]
Yes, that's fine.

**Comment by divyav2020** [comment]
We have updated in staging

**Comment by ertjlane** [comment]
This appears to be resolved in staging!
