### ISSUE TITLE
Cortex Error - Survey_Scores.py

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#719]
**Describe the bug**
When attempting to process dictionary assigned survey scores from mindLAMP into a dataframe, I receive the error 'invalid literal for int() with base 10: '"None"''. This appears to be the response to a NULL value in a survey response, the source of which I cannot place. 

**To Reproduce**
Go to home/erlend/schz SF/NIH2_data and run kernal. The error should emerge in cell 13. Unclear if this is a cortex bug or not, but passing it on here either way per recommendation of the assignees. 

<img width="1054" alt="Screen Shot 2022-12-05 at 4 54 58 PM (2)" src="https://user-images.githubusercontent.com/104088715/205750741-0ef21a3e-7c24-456c-8d12-6c150d608469.png">

**Comment by lugray1** [comment]
This has been resolved by adding a try-except-else block in Erlend's cortex to the 'score_question' function in the cortex primary survey_scores feature. The data that was causing this error is from 2017, so we are not adding this try block to cortex itself because this is not something we are encountering in current projects and data analysis.
