### ISSUE TITLE
mindLAMP Activities Not Loading

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#724]
**Describe the bug**
Activities within the app are not loading, but are endlessly buffering. This is true across devices (smartphones and desktop), and across mindLAMP servers. It occurred shortly after [this update](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/releases/tag/2022.12.20) to mindLAMP. This has occurred in previous updates, but never for this long. Because this appears to be an issue with the update instantiating, this issue will not be present on dashboard-staging.
![mindlamp error](https://user-images.githubusercontent.com/104088715/208924365-6b59714b-ebdd-4aed-9926-b481573a872a.jpg)

**To Reproduce**
Go to lamp-dashboard, or any lamp account and open an activity - could be learn, manage, or otherwise, the result has been the same.

**Comment by falmeida-orangeloops** [comment]
Working on it

**Comment by falmeida-orangeloops** [comment]
@ertjlane Here's what I found:

When the dashboard is going to load an activity, it makes a request to GitHub to retrieve the HTML source of the activity from a file in the [BIDMCDigitalPsychiatry/LAMP-activities](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities) repository. Which file is downloaded depends on whether you are in dev or in production environment. For example, if I try to access a journal activity from the staging dashboard (dev environment) the file from the following URL is retrieved:
<pre>
https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/<b>dist</b>/out/journal.html.b64
</pre>
This means the [`out/journal.html.b64` file](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/dist/out/journal.html.b64) from the `dist` branch. On the other hand, if you use the production dashboard (production environment), the following URL is used:
<pre>
https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/<b>latest</b>/out/journal.html.b64
</pre>
This points to the `out/journal.html.b64` file from the `latest` branch. The problem is that the `latest` branch does not exist in this repo, so the request returns 404. The dashboard lacks visual error handling for this, so it shows the loading indicator, but actually the problem is that it didn't find the file it is looking for.

I don't know about your deployment process, but it seems like the BIDMCDigitalPsychiatry/LAMP-activities repo must have a `latest` branch with an `out` directory (similar to the one in the `dist` branch) for the dashboard to work on production. Could you confirm that?

**Comment by falmeida-orangeloops** [comment]
Actually it seems like `latest` is supposed to be [a tag](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/releases/tag/latest), not a branch. The file tree of the [commit](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/commit/b41a50eba79cba9a5005b6a7f2a44a0e71a4fd3c) that your `latest` tag is pointing to [does not contain the `out` directory](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/tree/b41a50eba79cba9a5005b6a7f2a44a0e71a4fd3c). You need to update that tag to a commit that does.

**Comment by ertjlane** [comment]
Thanks for this Facundo! The issue has been resolved for the time being.
