### ISSUE TITLE
Exposure Module in mindLAMP Digital Clinic Not Appearing

### ISSUE THREAD

**Issue by ertjlane** [BIDMCDigitalPsychiatry/LAMP-platform#725]
**Describe the bug**
Question labels are not appearing for a specific activity in the manage section of the ''vqgvp6v3axr0mbst1nrx' investigator account. This is not occurring on other activities within the investigator account, or other activities on mindLAMP. Note: when going into edit activities, questions are written out as they should be in the editor. Not all of the questions have missing descriptions, but the majority do. Please let me know if additional information is required.

**To Reproduce**
log into mindLAMP - api.lamp.digital. (production or staging dashboard)
go to 'vqgvp6v3axr0mbst1nrx'
Go into dummy account
Go into manage.
Open 'Exposure'.

**Screenshots**
<img width="1440" alt="Screen Shot 2022-12-22 at 1 52 02 PM" src="https://user-images.githubusercontent.com/104088715/209206439-0237c462-902d-4feb-8105-5bf4b62b4a0d.png">

<img width="1440" alt="Screen Shot 2022-12-22 at 1 51 49 PM" src="https://user-images.githubusercontent.com/104088715/209206455-68e09c1f-efe8-4710-bc2e-ad4ab47d79dc.png">

**Comment by falmeida-orangeloops** [comment]
Noted, will try to take a look before the end of tomorrow.

**Comment by falmeida-orangeloops** [comment]
Found the source of this issue. It is related to translations ([relevant i18next issue](https://github.com/i18next/react-i18next/issues/387)). In short, this results in question labels ending with a colon being "hidden".

We have at least two options:
1. Remove the trailing colon from all question labels in that particular activity (quickest fix).
2. Add the following line [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/blob/b41a50eba79cba9a5005b6a7f2a44a0e71a4fd3c/Survey/src/i18n.js#L191):
   ```
   nsSeparator: false,
   ```
   This is in my opinion the best one because it would prevent you from running into this issue in the future. I can do it if it's okay for you.

**Comment by ertjlane** [comment]
Yes, option two sounds great, thank you!

**Comment by falmeida-orangeloops** [comment]
I think most probably yes.

Done and merged! BIDMCDigitalPsychiatry/LAMP-activities#242

**Comment by ertjlane** [comment]
Great, this looks like it's fixed in testing!
